User.create!(email: "hire@me.com", password: "password")

# Bookmark.create!(user_id: 1, url: "www.gamefaqs.com", title: "Pokemon X", summary: "summary1", is_favorited: true)
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.amazon.com", title: "Kirkland Real Sliced Freeze-Dried Fruit Snacks Variety Pack", summary: "summary2", is_favorited: true)
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.reddit.com", title: "Downhill longboarding.", summary: "summary3")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Android: The Land That Python Forgot", summary: "summary4")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.gamefaqs.com", title: "Andreessen Horowitz Sells a Third of its Facebook Shares", summary: "summary5", is_favorited: true)
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.amazon.com", title: "Sprite Lamp", summary: "summary6", is_favorited: true)
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.reddit.com", title: "Stop the NSA 'Fake Fix' Bill", summary: "summary7")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Super Soaker creator awarded $72.9M from Hasbro", summary: "summary8")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Scaling Scala vs Java", summary: "summary0")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "The Big Data Brain Drain: Why Science is in Trouble", summary: "summary10")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Mistakes made and addressed", summary: "summary11")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "HostDB", summary: "summary12")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Ulam spiral", summary: "summary13")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "A History of Political Correctness", summary: "summary14")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "High-Resolution Mandelbrot in Obfuscated Python", summary: "summary15")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "From a Model S owner in Tennessee", summary: "summary16")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Ask HN: How to safely switch to programming?", summary: "summary17")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Ask HN: What's the best companies to work in US which don't have media coverage", summary: "summary18")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Shopify accepts Bitcoin", summary: "summary19")
# sleep(2)
# Bookmark.create!(user_id: 1, url: "www.ebay.com", title: "Is economics a science?", summary: "summary20")